# See https://wiki.hypr.land/Configuring/Monitors/

# Configuração do PC 
monitor = DP-1, highrr, 0x0, 1

# Configuração do Notebook 
monitor = eDP-1, preferred, 0x0, 1.33

# Regra Coringa 
monitor = , preferred, auto, 1