# See https://wiki.hypr.land/Configuring/Monitors/

# Configuração do PC 
# monitor = HDMI-A-1, highrr, 0x1, 1

# Configuração do Notebook 
monitor = eDP-1, preferred, 0x0, 1
monitor = HDMI-A-1, preferred, auto-left, 1


# Regra Coringa 
monitor = , preferred, auto, 1
